# Generated by Django 4.2 on 2025-06-18 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cannabis', 'Cannabis'), ('alcohol', 'Alcohol'), ('both', 'Cannabis & Alcohol')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'db_table': 'vendor_categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('hours_monday', models.CharField(blank=True, default='9:00 AM - 9:00 PM', max_length=50)),
                ('hours_tuesday', models.CharField(blank=True, default='9:00 AM - 9:00 PM', max_length=50)),
                ('hours_wednesday', models.CharField(blank=True, default='9:00 AM - 9:00 PM', max_length=50)),
                ('hours_thursday', models.CharField(blank=True, default='9:00 AM - 9:00 PM', max_length=50)),
                ('hours_friday', models.CharField(blank=True, default='9:00 AM - 10:00 PM', max_length=50)),
                ('hours_saturday', models.CharField(blank=True, default='9:00 AM - 10:00 PM', max_length=50)),
                ('hours_sunday', models.CharField(blank=True, default='10:00 AM - 8:00 PM', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('google_place_id', models.CharField(blank=True, max_length=200, unique=True)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('google_review_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='vendors.vendorcategory')),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['latitude', 'longitude'], name='vendors_latitud_6929a6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category', 'is_active'], name='vendors_categor_76f097_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_featured', 'rating'], name='vendors_is_feat_f4dcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['google_place_id'], name='vendors_google__26b286_idx'),
        ),
    ]
