# Generated by Django 4.2 on 2025-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_review_product_review_reviews_vendor__32d0c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategory',
            name='name',
            field=models.CharField(choices=[('cannabis', 'Cannabis'), ('alcohol', 'Alcohol'), ('both', 'Cannabis & Alcohol'), ('wellness', 'Wellness'), ('food', 'Food & Beverage'), ('retail', 'Retail'), ('service', 'Service'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
