# Generated by Django 4.2 on 2025-06-18 07:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deal_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed_amount', 'Fixed Amount Off'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Deal'), ('special', 'Special Offer')], max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('savings_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity_available', models.IntegerField(blank=True, null=True)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('min_age_required', models.IntegerField(default=19)),
                ('max_per_customer', models.IntegerField(blank=True, null=True)),
                ('requires_membership', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-is_featured', '-discount_percentage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Deal Categories',
                'db_table': 'deal_categories',
            },
        ),
        migrations.CreateModel(
            name='UserDealInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('click', 'Clicked'), ('save', 'Saved'), ('share', 'Shared'), ('redeem', 'Redeemed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_deal_interactions',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.dealcategory'),
        ),
        migrations.AddField(
            model_name='deal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='userdealinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='user_deal_i_user_id_ea1444_idx'),
        ),
        migrations.AddIndex(
            model_name='userdealinteraction',
            index=models.Index(fields=['deal', 'interaction_type'], name='user_deal_i_deal_id_f2591d_idx'),
        ),
        migrations.AddIndex(
            model_name='userdealinteraction',
            index=models.Index(fields=['timestamp'], name='user_deal_i_timesta_1780df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdealinteraction',
            unique_together={('user', 'deal', 'interaction_type')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['vendor', 'is_active'], name='deals_vendor__ed1efc_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date', 'end_date'], name='deals_start_d_f44f07_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_featured', 'discount_percentage'], name='deals_is_feat_247562_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['product_category', 'is_active'], name='deals_product_930f8d_idx'),
        ),
    ]
