# Generated by Django 4.2 on 2025-06-18 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('search_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'search_locations',
            },
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_km', models.IntegerField(default=25)),
                ('results_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_searches',
            },
        ),
        migrations.AddIndex(
            model_name='searchlocation',
            index=models.Index(fields=['city', 'province'], name='search_loca_city_97be55_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlocation',
            index=models.Index(fields=['search_count'], name='search_loca_search__1f2599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchlocation',
            unique_together={('name', 'city', 'province')},
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['user', 'timestamp'], name='user_search_user_id_68242c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['latitude', 'longitude'], name='user_search_latitud_071876_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['timestamp'], name='user_search_timesta_d35ee4_idx'),
        ),
    ]
