# GitHub Actions CI/CD Pipeline for Frontend
name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: npm ci
      
    # - name: Run frontend tests
    #   run: npm test -- --coverage --watchAll=false
      
    - name: Build React app
      run: npm run build

  deploy:
    needs: frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Vercel
      run: echo "Frontend automatically deploys to Vercel on push to main"
    
    # The frontend is already deployed via Vercel integration
    # Backend is now in a separate repository
